name: smackapi-release
home: https://github.com/alex-egorov/brigade-smackapi
version: 1.1
description: Simple web app for demonstrating Kubernetes
maintainers: 
  - name: Alex Egorov
    email: alex202@egorov.net
